---

name: Build & Publish

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  release:
    types:
      - created
  schedule:
    - cron: "0/10 * * * *"
#    - cron: "0 18 * * 5"

jobs:
  build-publish:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/karras/archlinux-package-build:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Refresh and update packages
        run: |
          pacman -Syu --noconfirm

      - name: Import builder private key for package signing
        run: |
          echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | sudo -u builder gpg --import --batch --no-tty

      - name: Initialize pacman secret key, import and trust builder public key
        run: |
          pacman-key --init
          pacman-key --add builder_public_key.asc
          pacman-key --lsign-key 25267573FD638312C5EBE4C40C758F9503EDE7AF

      - name: Build packages
        run: |
          sudo -u builder \
            PACKAGE_AUTHOR="Builder <builder@0x539.ch>" \
            PACKAGE_GPG_ID=25267573FD638312C5EBE4C40C758F9503EDE7AF \
            ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: /home/builder/build/*

      - name: Add packages to the 'latest' release
        if: github.event_name == 'schedule'
        run: |
          pacman -S curl --noconfirm
          RELEASE="latest"

          for FILE in /home/builder/build/*; do
            curl -sSL \
                 -X POST \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -T ${FILE} \
                 --header "Content-Type: application/octet-stream" \
                 https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE}/assets?name=${FILE##*/}
          done

      - name: Add packages to the new release
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          pacman -S curl jq --noconfirm
          RELEASE=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")

          for FILE in /home/builder/build/*; do
            curl -sSL \
                 -X POST \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -T ${FILE} \
                 --header "Content-Type: application/octet-stream" \
                 https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE}/assets?name=${FILE##*/}
          done
